### ISSUE TITLE
Experiment Result

### ISSUE THREAD

**Issue by jamesgzl** [hjxwhy/mipnerf_pl#1]
Hey and Thanks for sharing ur mip-nerf code.
I am currently doing something base on ur code. I wonder whether this code on the same experiment of paper? 
See your reply! love u

**Comment by hjxwhy** [comment]
@jamesgzl Hey, I am now doing the experiments as the paper, but the result is a little bad compared with the paper. I will try to find out the bugs.

**Comment by atztao** [comment]
hey, thanks for your share, if the code combine with the framework of the instant-gp https://github.com/NVlabs/instant-ngp , maybe better.

**Comment by hjxwhy** [comment]
hey @atztao, It's an idea, I have read instant-ngp paper but the code is cuda, which is difficult and I still read the code. But I have no idea now how to connect the mipnerf IPE with ngp's hash table encode. Another good news is that this repo can replicate the result, I can almost reach the result with paper, I will update readme lately!

**Comment by atztao** [comment]
Good news, i think maybe can replaced the RGB_network of instant-ngp by the mip-nerf, and the encoding not changed. And also, the new mip-nerf-360 in your plan ?

**Comment by jamesgzl** [comment]
Hey! Good to hear the experiment can be repulica!
if i train mipnerf in a real world dataset, shall i use cylinder_to_gaussian instead of conical_frustum_to_gaussian?

**Comment by hjxwhy** [comment]
> Good news, i think maybe can replaced the RGB_network of instant-ngp by the mip-nerf, and the encoding not changed. And also, the new mip-nerf-360 in your plan ?

Maybe I have no time to replicate mipnerf360, but I have read the paper carefully. I want to spend time to read instant-ngp code carefully!

**Comment by hjxwhy** [comment]
> Hey! Good to hear the experiment can be repulica! if i train mipnerf in a real world dataset, shall i use cylinder_to_gaussian instead of conical_frustum_to_gaussian?

It is depend on your data format, If it is forward face scene, NDC space or mipnerf conical don't have  great gap, but if your data is 360 degrees, you should better use conical_frustum_to_gaussian

**Comment by jamesgzl** [comment]
感谢回复！这个邮箱地址就是我的联系方式，我们可以加个好友一起讨论一哈嘛😁






------------------ Original ------------------
From: Jianxin Huang ***@***.***&gt;
Date: Sun,May 8,2022 11:06 PM
To: hjxwhy/mipnerf_pl ***@***.***&gt;
Cc: JamesGZL ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [hjxwhy/mipnerf_pl] Experiment Result (Issue #1)





  
Hey! Good to hear the experiment can be repulica! if i train mipnerf in a real world dataset, shall i use cylinder_to_gaussian instead of conical_frustum_to_gaussian?
  
It is depend on your data format, If it is forward face scene, NDC space or mipnerf conical don't have  great gap, but if your data is 360 degrees, you should better use conical_frustum_to_gaussian

**Comment by atztao** [comment]
不如咱三加个微信 仔细交流交流

**Comment by jamesgzl** [comment]
我建立了一个qq群，二位有空的时候可以添加一下 咱们一起讨论😁


234389052



发自我的iPhone


------------------ Original ------------------
From: 张陶 ***@***.***&gt;
Date: Sun,May 8,2022 11:16 PM
To: hjxwhy/mipnerf_pl ***@***.***&gt;
Cc: JamesGZL ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [hjxwhy/mipnerf_pl] Experiment Result (Issue #1)





 
不如咱三加个微信 仔细交流交流

**Comment by hjxwhy** [comment]
@jamesgzl 加了~~

**Comment by AlphaPlusTT** [comment]
@hjxwhy 你好我这段时间在我之前写的那个mipnerf-pytorch上又尝试了一些复现和修改，但是性能跟jax版本还是差了很多，能否请教一下您这边是在我那个mipnerf-pytorch的基础上主要修改了哪些bug？

**Comment by jamesgzl** [comment]
这个上面不太方便发联系方式呀😂



发自我的iPhone


------------------ Original ------------------
From: 张陶 ***@***.***&gt;
Date: Sun,May 8,2022 11:16 PM
To: hjxwhy/mipnerf_pl ***@***.***&gt;
Cc: JamesGZL ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [hjxwhy/mipnerf_pl] Experiment Result (Issue #1)





 
不如咱三加个微信 仔细交流交流

**Comment by xiyichen** [comment]
Hi @hjxwhy, thanks a lot for your implementation in PyTorch. Have you found the reason that makes this re-implementation perform worse than the original JAX implementation?
