### ISSUE TITLE
Script for visualizing poses

### ISSUE THREAD

**Issue by addy1997** [hjxwhy/mipnerf_pl#10]
Hi @hjxwhy,

This is amazing work. If you don't mind, may I ask which scripts are used for visualizing poses?

**Comment by hjxwhy** [comment]
Thanks, you can visualize poses using this script https://github.com/hjxwhy/mipnerf_pl/blob/dev/utils/visualize_cameras.py

**Comment by addy1997** [comment]
> Thanks, you can visualize poses using this script https://github.com/hjxwhy/mipnerf_pl/blob/dev/utils/visualize_cameras.py

Thanks
