### ISSUE TITLE
OSError: /usr/local/lib/python3.7/dist-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN3c1022getCustomClassTypeImplERKSt10type_index [ ] Colab paid products - Cancel contracts here

### ISSUE THREAD

**Issue by Miriam2040** [hjxwhy/mipnerf_pl#12]
Hi, I am getting the following error in train, any idea? Thanks!

OSError: /usr/local/lib/python3.7/dist-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN3c1022getCustomClassTypeImplERKSt10type_index

**Comment by hjxwhy** [comment]
Maybe you should install correctly version torchtext with pytorch https://github.com/pytorch/text/#installation, my code don't use torchtext.

**Comment by Miriam2040** [comment]
I believe the root cause is that I am trying to run the code in google colab which is python 3.7.
Any instructions on how to reproduce the results in such environment? I am getting error when trying to install the requirements

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.13.1+cu113 requires torch==1.12.1, but you have torch 1.11.0 which is incompatible.
torchtext 0.13.1 requires torch==1.12.1, but you have torch 1.11.0 which is incompatible.
torchaudio 0.12.1+cu113 requires torch==1.12.1, but you have torch 1.11.0 which is incompatible.
google-colab 1.0.0 requires tornado~=5.1.0, but you have tornado 6.2 which is incompatible.
flask 1.1.4 requires Jinja2<3.0,>=2.10.1, but you have jinja2 3.1.2 which is incompatible.

**Comment by hjxwhy** [comment]
Can you install the latest version pytorch in google colab? or upgrade the python version, I have never tried in python 3.7, and you can not install torchtext. The problem you show just the version incompatible.
