### ISSUE TITLE
A question about environment

### ISSUE THREAD

**Issue by ZYY-666** [hjxwhy/mipnerf_pl#13]
I followed the steps in readme file, and when I did the last step(pip install -r requirements.txt), the system automatically reinstalled torch during the installation process, but there were already separate steps to install torch and torch vision("pip3 install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu113" of readme file).
![image](https://user-images.githubusercontent.com/69071467/187577867-b7864398-63bb-45d3-a110-f566c5ca52b1.png)
Also, at the end, the system tried uninstalling torch-1.12.1 and cu113, and after uninstalling them, it said that the torch version was incompatible.
As shown in the figure below
![image](https://user-images.githubusercontent.com/69071467/187577978-8f562f83-79f4-4731-9d67-7dcde6d66cdc.png)

**Comment by ZYY-666** [comment]
Then I did the step "pip3 install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu113" again, the system uninstalled torch 1.11 and reinstalled torch 1.12. However, there was a new version incompatibility issue, functorch 0.1.1 seems to require torch to be 1.11.
As shown in the picture below:
![image](https://user-images.githubusercontent.com/69071467/187578978-957a95c0-f4f4-45f0-9c01-e6abe3bc336e.png)

**Comment by hjxwhy** [comment]
Oh, I am sorry for this, I remove the functorch now, it is not used in mipnerf, just my try in mipnerf360, but now I have given up trying it(because I decide to use JAX for my next research). You can remove all functions about functorch.
