### ISSUE TITLE
Training duration

### ISSUE THREAD

**Issue by gkouros** [hjxwhy/mipnerf_pl#4]
Hi.

How long does it take to train on the Lego scene for 300k epochs? Also, why 300k and not 1M epochs like in the official mipnerf implementation?

**Comment by hjxwhy** [comment]
My NVIDIA 3090ti was limited power to 150w, so it is very slow, I remember 300k takes 2.5 days. I stop it at 300k because the result was almost the same as the paper.

**Comment by gkouros** [comment]
Thanks for the info!
