### ISSUE TITLE
question about dataset

### ISSUE THREAD

**Issue by menglongyue** [hjxwhy/mipnerf_pl#5]
Hello, thanks for your excellent work, I have noticed the Jax version and your implementation of mip-nerf have only test on blender dataset, and do not test on other datasets, like llff dataset. Is this implementation only works for blender dataset? can you do some  experiments on llff dataset?

**Comment by hjxwhy** [comment]
I am sorry I have no time to test it. If you have time you can test and report the result, feel free to contribute!
